name: Create Project Issues

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install @actions/core @actions/github gray-matter markdown-table

      - name: Create Issues
        run: node .github/scripts/create_issues.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
